id: IFFFBDBBB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:07:04+00:00'
last_modified: '2022-06-09T07:37:57.076974+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18538
  title: སྦྱོང་བྱེད་ལས།  བཅོས་སྒྲིག་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    675B:
      image_group_id: I8LS18540
      title: Volume 1 of byong byed las/__bcos sgrig ma/
      total_pages: 173
      order: 1
      base_file: 675B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
