id: P007929
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18538
  title: སྦྱོང་བྱེད་ལས།  བཅོས་སྒྲིག་མ།
  author: ''
  volumes:
    f96c776f19ce4979a52bac60e912b3a0:
      image_group_id: I8LS18540
      title: ''
      volume_number: 1
      total_pages: 173
ebook_metadata:
  title: སྦྱོང་བྱེད་ལས།  བཅོས་སྒྲིག་མ།
  author: ''
  sku: P007929
  cover: cover.jpg
  layers:
  - pagination
